stm_bm(["menu14ac",730,"menu","blank.gif",0,"","",1,1,0,0,800,1,0,0,"","1024",0,0,1,1,"default","hand","menu/"],this);
stm_bp("p0",[0,4,0,0,0,0,0,0,100,"",-2,"",-2,90,0,0,"#ffffff","transparent","bg_02.gif",3,1,1,"#AFC6ED"]);
stm_ai("p0i0",[2,"","0503-start.jpg","0503-start1.jpg",93,27,0,"","_self","","დააწკაპუნეთ აქ","","",0,0,0,"","",0,0,0,0,1,"#ffffff",1,"#ffffff",1,"","",3,3,0,0,"#ffffff #ffffff #ffffff #ffffff","#ffffff #ffffff #ffffff #ffffff","#000000","#000000","9pt Arial","9pt Arial",0,0]);

stm_bp("p1",[1,3,3,0,0,0,27,6,100,"",-2,"",-2,100,2,3,"#666666","#dedede","0503-sline1.jpg",3,1,1,"#6a8cdd"]);
stm_aix("p1i0","p0i0",[0,"კონსპექტები,პროექტები...","","",-1,-1,0,"","_self","","","download.gif","download.gif",27,27,0,"arrow.gif","arrow.gif",5,7,0,0,1,"#ffffff",1,"#bbe6ff",0,"","",3,3,0,0,"#edeae6 #666666 #666666 #edeae6","#666666 #edeae6 #edeae6 #666666","#000000","#000000","8pt Verdana","8pt Verdana"],210,0);

stm_bpx("p2","p1",[1,2,0,0,0,0,27,6,100,"",-2,"",-2,100,2,3,"#666666","#dedede","0503-sline1.jpg",2]);
stm_aix("p2i0","p1i0",[0,"ლექციის კონსპექტები","","",-1,-1,0,"","_self","","","lectures.gif","lectures.gif",27,27,0,"arrow.gif","arrow.gif",5,7,0,0,1,"#ffffff",1,"#bbe6ff",0,"","",2],200,0);

stm_bpx("p3","p2",[1,2,0,0,0,6,0,0]);
stm_aix("p3i0","p2i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_01.pdf\"><img src=\"images/pdf.gif\"  /> 1-ი ლექცია: DevC++-ის მომართვა და ბაზური აპლიკაცია</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i1","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_02.pdf\"><img src=\"images/pdf.gif\"  /> 2-ე ლექცია: OpenGL-ის მიმოხილვა და გრაფიკული კონვეირი</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i2","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_03.pdf\"><img src=\"images/pdf.gif\"  /> 3-ე ლექცია: კოორდინატების ტრანსფორმაცია და პროექცია</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i3","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_04.pdf\"><img src=\"images/pdf.gif\"  /> 4-ე ლექცია: განათება და მატერიალები</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i4","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_05.pdf\"><img src=\"images/pdf.gif\"  /> 5-ე ლექცია: ტექსტურირება</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i5","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_06.pdf\"><img src=\"images/pdf.gif\"  /> 6-ე ლექცია: GLUT-ში რამოდენიმე ფანჯრის და მენიუს შექმნა</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i6","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_07.pdf\"><img src=\"images/pdf.gif\"  /> 7-ე ლექცია: მულტიტექსტურირება და სტენსილ ბუფერი</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i7","p3i0",[1,"<a class=\"menuItem\" href=\"samples/advtexturing.zip\"><img src=\"images/devcpp.gif\"  /> 7-ე ლექციის სავარჯიშო პროექტი (advtexturing)</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i8","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/opengl_08.pdf\"><img src=\"images/pdf.gif\"  /> 8-ე ლექცია: აკუმულაციის ბუფერი და არჩევის რეჟიმი</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p3i9","p3i0",[1,"<a class=\"menuItem\" href=\"lectures/lectures.zip\"><img src=\"images/msword.gif\"  /> გაერთიანებული არქივი Word-ის ფორმატში</a>","","",-1,-1,0,"","_self","","","","",0,0,0,"","",0,0]);


stm_ep();
stm_aix("p2i1","p2i0",[0,"DEVC++-ის პროექტები","","",-1,-1,0,"","_self","","","devcpp.gif","devcpp.gif",27,27,0,"arrow.gif","arrow.gif",5,7,0,0,1,"#feeab6"],200,0);
stm_bpx("p4","p2",[1,2,0,0,0,6,0]);
stm_aix("p4i0","p2i0",[0,"ბაზური აპლიკაცია","","",-1,-1,0,"","_self","","","","",0,0]);
stm_bpx("p5","p3",[]);
stm_aix("p5i0","p3i0",[1,"<a href=\"samples/opengl_01_src.zip\"><img src=\"images/app_01.jpg\"/> </a>"]);
stm_aix("p5i1","p3i0",[1,"მინიმალური OpenGL აპლიკაცია. იხატება თეთრი<br/> კვადრატი"]);
stm_ep();
stm_aix("p4i1","p4i0",[0,"მარტივი ფიგურების ხატვაა"]);
stm_bpx("p6","p3",[]);
stm_aix("p6i0","p5i0",[1,"<a href=\"samples/opengl_02_src.zip\"><img src=\"images/app_02.jpg\"/> </a>"]);
stm_aix("p6i1","p5i1",[0,"იხატება 2 ფიგურა. სამკუთხედი და კვადრატი"]);
stm_ep();
stm_aix("p4i2","p4i0",[1,"შეფერადება(shading)"]);
stm_bpx("p7","p3",[]);
stm_aix("p7i0","p5i0",[1,"<a href=\"samples/opengl_03_src.zip\"><img src=\"images/app_03.jpg\"/> </a>"]);
stm_aix("p7i1","p5i1",[0,"შეფერადება(shading)"]);
stm_ep();
stm_aix("p4i3","p4i0",[1,"ანიმაცია"]);
stm_bpx("p8","p3",[]);
stm_aix("p8i0","p5i0",[1,"<a href=\"samples/opengl_04_src.zip\"><img src=\"images/app_04.jpg\"/> </a>"]);
stm_aix("p8i1","p5i1",[0,"ფიგურების მარტივი ანიმაცია - მობრუნება"]);
stm_ep();
stm_aix("p4i4","p4i0",[1,"3D ობიექტები"]);
stm_bpx("p9","p3",[]);
stm_aix("p9i0","p5i0",[1,"<a href=\"samples/opengl_05_src.zip\"><img src=\"images/app_05.jpg\"/> </a>"]);
stm_aix("p9i1","p5i1",[0,"3D ობიექტები"]);
stm_ep();
stm_aix("p4i5","p4i0",[1,"ანიმაცია და კლავიატურა"]);
stm_bpx("p10","p3",[]);
stm_aix("p10i0","p5i0",[1,"<a href=\"samples/opengl_06_src.zip\"><img src=\"images/app_06.jpg\"/> </a>"]);
stm_aix("p10i1","p5i1",[1," <ul><li>'d' - დედამიწის მობრუნება</li><li>'y'-დედამისი დატრიალება მზის გარშემო</li></ul>"]);
stm_ep();
stm_aix("p4i6","p4i0",[1,"ანიმაცია და კოორდინატების ტრანსფორმაცია"]);
stm_bpx("p11","p3",[]);
stm_aix("p11i0","p5i0",[1,"<a href=\"samples/opengl_06_1_src.zip\"><img src=\"images/app_061.jpg\"/> </a>"]);
stm_aix("p11i1","p5i1",[1,"ესაა წინა პროგრამის ოდნავ გართულება.<br/> დამატებულია მთვარეც"]);
stm_ep();
stm_aix("p4i7","p4i0",[1,"Display List"]);
stm_bpx("p12","p3",[]);
stm_aix("p12i0","p5i0",[1,"<a href=\"samples/opengl_07_src.zip\"><img src=\"images/app_07.jpg\"/> </a>"]);
stm_aix("p12i1","p5i1",[0,"Display List-ებს შექმნა და გამოყენება პროგრამაში"]);
stm_ep();
stm_aix("p4i8","p4i0",[1,"ხატვა შერეული მასივებით"]);
stm_bpx("p13","p3",[]);
stm_aix("p13i0","p5i0",[1,"<a href=\"samples/opengl_08_src.zip\"><img src=\"images/app_08.jpg\"/> </a>"]);
stm_aix("p13i1","p5i1",[1,"შერეული მასივების გამოყენებით გეომეტრიული<br/> ინფორმაციის მიწოდება და რენდერი"]);
stm_ep();
stm_aix("p4i9","p4i0",[1,"პროგრამულად გეომეტრიის გენერაცია"]);
stm_bpx("p14","p3",[]);
stm_aix("p14i0","p5i0",[1,"<a href=\"samples/opengl_09_src.zip\"><img src=\"images/app_09.jpg\"/> </a>"]);
stm_aix("p14i1","p5i1",[1,"2 ფიგურის გენერაცია პროგრამულად და თაგუნიას<br/> დამუშავება.<ul><li>’c’ - გენერირებული მოდელის<br/> ჩატვირთვა/შეცვლა.</li><li>'w' - შეფერადება/ხაზებით ხატვის<br/> რეჟიმზე გადართვა</li></ul></div>"]);
stm_ep();
stm_aix("p4i10","p4i0",[1,"მარტივი ტექსტურირება"]);
stm_bpx("p15","p3",[]);
stm_aix("p15i0","p5i0",[1,"<a href=\"samples/texturing_01.zip\"><img src=\"images/simpletexturing.jpg\"/> </a>"]);
stm_aix("p15i1","p5i1",[1,"იტვირთება კონკრეტული JPEG ტექსტურა <br/>textures-დირექტორიიდან და ხდება მისი<br/> დადება QUAD-ზე. შეგიძლიათ შეცვალოთ<br/> კოდი და ჩატვირთოთ სხვადასხვა ტექსტურები."]);
stm_ep();
stm_aix("p4i11","p4i0",[1,"ავტომატური ტექსტურირება"]);
stm_bpx("p16","p3",[]);
stm_aix("p16i0","p5i0",[1,"<a href=\"samples/texturing_02.zip\"><img src=\"images/texturing2.jpg\"/> </a>"]);
stm_aix("p16i1","p5i1",[1,"იტვირთება 2 JPEG ტექსტურა.<br/> '1', '2' და '3'-ით ხდება ტექსტურების და <br/> ავტომატური მეფირების რეჟიმების შეცვლა"]);
stm_ep();
stm_aix("p4i12","p4i0",[1,"ტექსტურის დამისამართება"]);
stm_bpx("p17","p3",[]);
stm_aix("p17i0","p5i0",[1,"<a href=\"samples/texturing_03.zip\"><img src=\"images/texturing3.jpg\"/> </a>"]);
stm_aix("p17i1","p5i1",[1,"<div> პროგრამა დემოსტრაციას აკეთებს,<br/> თუ როგორ იცვლება ტექსტურის დამისამართების<br/> რეჟიმები როდესაც კოორდინატები გაცდება<br/> დასაშვებ საზღვრებს [0,1]<br/><ul><li>’1’ (ჩაიკეტოს)</li><li>’2’ (განმეორდეს)</li><li>’3’ (სარკისებულად აირეკლოს)</li></ul></div>"]);
stm_ep();
stm_aix("p4i13","p4i0",[1,"3ds ფაილიდან მოდელის ჩატვირთვა"]);
stm_bpx("p18","p3",[]);
stm_aix("p18i0","p5i0",[1,"<a href=\"samples/modelload.zip\"><img src=\"images/modelload.jpg\"/> </a>"]);
stm_aix("p18i1","p5i1",[1,"      <div>ტვირთავს გოგონას მოდელს 3ds ფაილიდან.<ul><li>’1’ არენდერებს წერტილებით</li><li>’2’ არენდერებს ხაზებით</li><li>’3’ არენდერებს ჩვეულებრივად</li></ul></div>"]);
stm_ep();
stm_aix("p4i14","p4i0",[1,"რამოდენიმე ფანჯრის შექმნა GLUT-ში"]);
stm_bpx("p19","p3",[]);
stm_aix("p19i0","p5i0",[1,"<a href=\"samples/multiwindow.zip\"><img src=\"images/multiview.jpg\"/> </a>"]);
stm_aix("p19i1","p5i1",[1,"პროგრამა ქმნის 3 ფანჯარას რომლებშიც<br/> იხატება ერთიდაიგივე სცენა სხვადასხვა კუთხით.<br/> სცენაზე მოძრაობა ხდება ისრების საშუალებით."]);
stm_ep();
stm_aix("p4i15","p4i0",[1,"კონტექსტური მენიუს შექმნა GLUT-ში"]);
stm_bpx("p20","p3",[]);
stm_aix("p20i0","p5i0",[1,"<a href=\"samples/contextmenu.zip\"><img src=\"images/contextmenu.jpg\"/> </a>"]);
stm_aix("p20i1","p5i1",[1,"კონტექსტური მენიუს და ქვემენიუების შექმნის<br/> და გამოყენების სადემონსტრაციო პროგრამა. "]);
stm_ep();
stm_aix("p4i16","p4i0",[1,"არეკვლის ეფექტი"]);
stm_bpx("p21","p3",[]);
stm_aix("p21i0","p5i0",[1,"<a href=\"samples/stencil_02.zip\"><img src=\"images/stencil2.jpg\"/> </a>"]);
stm_aix("p21i1","p5i1",[1,"სტენსილ ბუფერის გამოყენებით ხდება სარკისებური<br/> ზედაპირის რენდერი"]);
stm_ep();
stm_aix("p4i17","p4i0",[1,"სტენსილ ბუფერის გამოყენება"]);
stm_bpx("p22","p3",[]);
stm_aix("p22i0","p5i0",[1,"<a href=\"samples/stencil_01.zip\"><img src=\"images/stencil.jpg\"/> </a>"]);
stm_aix("p22i1","p5i1",[1,"სტენსილ ბუფერის გამოყენებით ხდება<br/> ჩატვირთული ობიექტის კონტურის ხატვა"]);
stm_ep();
stm_aix("p4i18","p4i0",[1,"აკუმულაციის ბუფერის გამოყენება"]);
stm_bpx("p23","p3",[]);
stm_aix("p23i0","p5i0",[1,"<a href=\"samples/GL_Accum.zip\"><img src=\"images/accum_02.jpg\"/><br/><img  src=\"images/accum_01.jpg\"/></a>"]);
stm_aix("p23i1","p5i1",[1,"      <ul><li>’s’ -”რბილი ჩრდილი”</li><li>’m’ -”გადღაბნილი მოძრაობა”</li></ul>"]);
stm_ep();
stm_aix("p4i19","p4i0",[1,"'ბრტყელი' ჩრდილები"]);
stm_bpx("p24","p3",[]);
stm_aix("p24i0","p5i0",[1,"<a href=\"samples/planarshadows.zip\"><img src=\"images/planarshadow.jpg\"/></a>"]);
stm_aix("p24i1","p5i1",[1,"მარტივი ჩრდილის რენდერი<br/> ჩრდილის მატრიცის გამოყენებით"]);
stm_ep();
stm_aix("p4i20","p4i0",[1,"ნორმალების შედარება"]);
stm_bpx("p25","p3",[]);
stm_aix("p25i0","p5i0",[1,"<a href=\"samples/Normals.zip\"><img src=\"images/normals.jpg\"/></a>"]);
stm_aix("p25i1","p5i1",[1,"      <ul><li>’1’ -წვეროების ან პოლიგონის<br/> ნორმალების არჩევა</li><li>’2’ -პოლიგონების შემართებელი ხაზების<br/> ხახების ხატვის ჩართვა/გამოთვა</li><li>’3’ -ნორმალების ხატვის ჩართვა/გამორთვა</li></ul>"]);
stm_ep();


stm_ep();
stm_aix("p2i2","p2i0",[0,"პროგრამები და პროექტები","","",-1,-1,0,"","_self","","","progs.gif","progs.gif",27,27,0,"arrow.gif","arrow.gif",5,7,0,0,1,"#feeab6"],200,0);
stm_bpx("p9","p4",[]);
stm_aix("p9i0","p4i0",[1,"შეყვარებული კუბი"]);
stm_bpx("p10","p3",[]);
stm_aix("p10i0","p5i0",[1,"<a href=\"samples/lovecube.zip\"><img src=\"images/lovecube.jpg\"/></a>"]);
stm_aix("p10i1","p5i1",[1,"კუბი 6 სხვადასხვა ტექსტურით + იწერება წვეროების<br/> კოორდინატები და იხატება<br/> საკოორდინატო ღერძებიც <br/>’1’ - საწყის სცენაზე დაბრუნება,<br/> ’2’ და ’3’:)</p></div>"]);
stm_ep();
stm_aix("p9i1","p4i0",[1,"მატერიალები"]);
stm_bpx("p11","p3",[]);
stm_aix("p11i0","p5i0",[1,"<a href=\"samples/opengl_10_src.zip\"><img src=\"images/app_10.jpg\"/></a>"]);
stm_aix("p11i1","p5i1",[1,"პროგრამა საშუალებას გვაძლევს ცვალოთ<br/> სხვადასხვა მატერიალები. <ul><li>F1,F2 და F3 წინასწარ განსაზღვრული<br/> მატერიალების დანიშვნა</li><li>'x','y' და 'z'  შესაბამისი ღერძების<br/> გარშემო მობრუნება</li><li>Space  კონკრეტული ფერის<br/> შეცვლა(RGB) ან ყველასი</li><li>'c' მოდელის შეცვლა</li><li>'A/a'  Ambient კომპონენტას მომატება/დაკლება</li><li>'D/d'  Diffuse კომპონენტას მომატება/დაკლება</li><li>'S/s'  Specular კომპონენტას მომატება/დაკლება</li><li>'E/e'  Emission კომპონენტას მომატება/დაკლება</li><li>'H/h'  Shininess კომპონენტას მომატება/დაკლება</li><li>'w'    გაფერადების ან ხაზებით<br/> ხატვის რეჟიმის  გადართვა </li></ul>"]);
stm_ep();
stm_aix("p9i2","p4i0",[1,"განათების ტიპები OpenGL-ში"]);
stm_bpx("p12","p3",[]);
stm_aix("p12i0","p5i0",[1,"<a href=\"samples/opengl_11_src.zip\"><img src=\"images/app_11.jpg\"/></a>"]);
stm_aix("p12i1","p5i1",[1,"SPACE-ის შეგიძლიათ გადართოთ და დააკვირდეთ <br/>სხვადასხვა განათების ტიპებს OpenGL-ში"]);
stm_ep();
stm_aix("p9i3","p4i0",[1,"მოფარფატე პეპლები"]);
stm_bpx("p13","p3",[]);
stm_aix("p13i0","p5i0",[1,"<a href=\"samples/butterfly_src.zip\"><img src=\"images/butterfly.jpg\"/></a>"]);
stm_aix("p13i1","p5i1",[1,"ტექსტურირების და გამჭირვალობის გამოყენებით<br/> ხდება 50 'პეპლის' დარენდერება ეკრანზე"]);
stm_ep();
stm_aix("p9i4","p4i0",[1,"სტერეო ’აფეთქება’ "]);
stm_bpx("p14","p3",[]);
stm_aix("p14i0","p5i0",[1,"<a href=\"samples/opengl_boom.zip\"><img src=\"images/stereo_boom.jpg\"/></a>"]);
stm_aix("p14i1","p5i1",[1,"  <img src=\"images/stereoglass.jpg\"/>(სტერეო ეფექტის დასანახად<br/> საჭიროა სტერეო სათვალეები)<div>პროგრამა საშუალებას გვაძლევს ცვალოთ<br/> სხვადასხვა მატერიალები. <br/><ul><li>'s' - სტერეო რეჟიმის ჩართვა გამორთვა </li><li>UP/DOWN - სტერეო წანაცვლების<br/> გაზრდა/შემცირება </li><li>'g' - R/G სტერეო რეჟიმზე გადართვა </li><li>'b' - R/B სტერეო რეჟიმზე გადართვ </li><li>'m' - Motion blur-ის ჩართვა/გამორთვა </li><li>SPACE ან click - აფეთქება </li><li>'/' და '*' - კამერის მიახლოება/დაცილება </li><li>'1','2','3','4' - მატერიალების შეცვლა </li></ul>"]);
stm_ep();
stm_aix("p9i5","p4i0",[1,"სტერეო ’მორფინგი’ "]);
stm_bpx("p15","p3",[]);
stm_aix("p15i0","p5i0",[1,"<a href=\"samples/morph3d.zip\"><img src=\"images/morph3d.jpg\"/></a>"]);
stm_aix("p15i1","p5i1",[1,"  <img src=\"images/stereoglass.jpg\"/>(სტერეო ეფექტის დასანახად<br/> საჭიროა სტერეო სათვალეები)<br/>ეს არის 'მორფინგ'-ის (კოორდინატების რეალურ<br/> დროში ცვლა და ერთი ობიექტის მეორეში გარდაქმნა)<br/> სადემონსრაციო პროგრამა.<br/><ul><li>’+/-’ - სტერეო წანაცვლების გაზრდა/შემცირება </li><li>SPACE - მატერიალების ჩართვა/გამორთვა </li><li>’a’ - ანიმაციის ჩართვა/გამორთვა </li><li>’w' - გაფერადების რეჟიმის ჩართვა/გამორთვა </li><li>'1','2','3','4', ’5’ - ობიექტის სირთულის გაზრდა </li></ul>"]);
stm_ep();
stm_aix("p9i6","p4i0",[1,"ბურთები"]);
stm_bpx("p16","p3",[]);
stm_aix("p16i0","p5i0",[1,"<a href=\"samples/balls.zip\"><img src=\"images/balls.jpg\"/></a>"]);
stm_aix("p16i1","p5i1",[1,"სტენსილ ბუფერის დახმარებით ხდება<br/> ე.წ. 'სარკის არეკვლის ეფექტის' მიღება."]);
stm_ep();
stm_aix("p9i7","p4i0",[1,"GPU Raytrace"]);
stm_bpx("p17","p3",[]);
stm_aix("p17i0","p5i0",[1,"<a href=\"samples/gpu_raytrace_src.zip\"><img src=\"images/raytrace.jpg\"/></a>"]);
stm_aix("p17i1","p5i1",[1,"სხივების ტრასირების ალგორითმის რეალიზაცია<br/> ვიდეო ადაპტერზე და შედეგების ეკრანზე<br/> გამოტანა. შესადარებლად მოყვანილია<br/> იგივე სცენა OpenGL-ზეც. გასაშვებად საჭიროა<br/> შეიდერების მხარდამჭერი ვიდეო."]);
stm_ep();
stm_aix("p9i8","p4i0",[1,"Tutors"]);
stm_bpx("p18","p3",[]);
stm_aix("p18i0","p5i0",[1,"<a href=\"apps/tutors-win32.zip\"><img src=\"images/tutors.jpg\"/></a>"]);
stm_aix("p18i1","p5i1",[1,"ყველა პროგრამა არის ინტერაქტიული.<br/> თაგუნიას დახმარებით შესაძლებელია ’კოდში’<br/> ცვლილებების შეტანა და შედეგის მყისიერი დაკვირვება.<br/> ამისთვის მწვანედ შეფერადებულ ადგილებზე<br/> დააჭირეთ თაგუნიას და ამოძრავეთ. <br/>მარჯვენა ღილაკზე დაწკაპუნებით ასევე შესაძლებელია<br/> მოდლების და სცნენის სხვადასხვა პარამეტრების<br/> დაყენება/შეცვლა."]);
stm_ep();
stm_aix("p10i8","p4i0",[1,"მზის სისტემა"]);
stm_bpx("p19","p3",[]);
stm_aix("p19i0","p5i0",[1,"<a href=\"samples/SOLAR.ZIP\"><img src=\"images/exam_2.jpg\"/></a>"]);
stm_aix("p19i1","p5i1",[1,"		<ul><li>'d' - სადემონსტრაციო რეჟიმის<br/> ჩართვა/გამორთვა</li><li>'space' - პაუზის ჩართვა/გამორთვა</li><li>'z' - კამერის საწყისი პოზიცია</li><li>'x' - კამერის გადატანა პლანეტაზე </li><li>'c' - კამერის გადატანა წინა პლანეტაზე</li><li>''' - საწყისი ხატვის რეჟიმის არჩევა. <br/>’კარკასული’</li><li>'1' - შეფერადებული ხატვის რეჟიმის არჩევა</li><li>'2' - განათების რეჟიმის არჩევა</li><li>'3' - ტექსტურირების რეჟჳმზე გადასვლა</li></ul>"]);
stm_ep();
stm_aix("p11i8","p4i0",[1,"მულტიტექსტურირება შეიდერით"]);
stm_bpx("p20","p3",[]);
stm_aix("p20i0","p5i0",[1,"<a href=\"samples/Shader_Multitext.zip\"><img src=\"images/shadermultitex.jpg\"/></a>"]);
stm_aix("p20i1","p5i1",[1,"GLSL-ის (OpenGL-ის ზედა დონის შეიდერული ენა)<br/> გამოყენებით ხდება 2 ტექსტურის დადება<br/> და ერთერთის ანიმირება.<br/> გასაშვებად საჭიროა შეიდერების მხარდამჭერი<br/> ვიდეო. "]);
stm_ep();


stm_ep();
stm_aix("p2i3","p2i2",[0,"წიგნები","","",-1,-1,0,"","_self","","","books.gif","books.gif",27,27,0,"arrow.gif","arrow.gif",5,7,0,0,1,"#feeab6"],200,0);
stm_bpx("p14","p4",[]);
stm_aix("p14i0","p4i0",[1,"<img src=\"images/pdf.gif\"/> OpenGL Red Book(Eng)"]);
stm_bpx("p15","p3",[]);
stm_aix("p15i0","p5i0",[1,"<a href=\"books/OpenGL_RedBook_eng.pdf\"><img src=\"images/openglredbook.jpg\"/></a>"]);
stm_aix("p15i1","p5i1",[1,"OpenGL is a powerful software<br/> interface for graphics hardware<br/> that allows graphics<br/> programmers to produce<br/> high-quality color images<br/> of 3D objects.<br/> The functions in the OpenGL<br/> library enable programmers<br/> to build geometric models<br/>,view models interactively in<br/> 3D space, control color<br/> and lighting, manipulate images,<br/> and perform such tasks<br/> as alpha blending, antialiasing,<br/> depth cueing, and texture<br/> mapping."]);
stm_ep();
stm_aix("p14i1","p4i0",[1,"<img src=\"images/pdf.gif\"/> OpenGL Red Book(Rus)"]);
stm_bpx("p16","p3",[]);
stm_aix("p16i0","p5i0",[1,"<a href=\"books/OpenGL_RedBook_rus.pdf\"><img src=\"images/redbookrus.jpg\"/></a>"]);
stm_aix("p16i1","p5i1",[1,"Эта книга является первым<br/> русским изданием третьей<br/> редакции официального руководства<br/> по обучению OpenGL,<br/> подготовленным Наблюдательным<br/> Советом по Архитектуре OpenGL<br/> и компанией SGI."]);
stm_ep();
stm_aix("p16i1","p4i0",[1,"<img src=\"images/pdf.gif\"/>A Mathematical Introduction with OpenGL"]);
stm_bpx("p17","p3",[]);
stm_aix("p17i0","p5i0",[1,"<a href=\"books/A Mathematical Introduction with OpenGL.pdf\"><img src=\"images/mathintroopengl.jpg\"/></a>"]);
stm_aix("p17i1","p5i1",[1,"This book is an introduction<br/> to 3-D computer graphics<br/> with particular emphasis<br/> on fundamentals<br/> and the mathematics underlying<br/> computer graphics.<br/> It includes descriptions<br/> of how to use the cross-platform<br/> OpenGL programming<br/> environment.<br/>It also includes source<br/> code for a ray tracing<br/> software package.<br/><a href=\"books/A Mathematical Introduction with OpenGL.source code.rar\"><img src=\"images/download.jpg\"  />წიგნის მაგალითები</a>"]);
stm_ep();
stm_aix("p17i1","p4i0",[1,"<img src=\"images/pdf.gif\"/>Advanced graphics programming using OpenGL"]);
stm_bpx("p18","p3",[]);
stm_aix("p18i0","p5i0",[1,"<a href=\"books/Advanced.Graphics.Programming.Using.OpenGL.pdf\"><img src=\"images/advprogopengl.jpg\"/></a>"]);
stm_aix("p18i1","p5i1",[1,"This book attempts to<br/> bring the computer graphics<br/> enthusiast, whether professional<br/> or amateur, beyond the basics<br/> covered in computer graphics<br/> texts, and introduce them<br/> to a mix of more intense <br/>practical and theoretical <br/>discussion that is hard to <br/>obtain outside of a professional<br/> computer graphics<br/> environment.<br/><a href=\"books/Advanced.Graphics.Programming.Using.OpenGL.source code.zip\"><img src=\"images/download.jpg\"  />წიგნის მაგალითები</a>"]);
stm_ep();
stm_ep();
stm_ep();

/*stm_aix("p1i1","p1i0",[0,"Internet","","",-1,-1,0,"","_self","","","0503-icon4.gif","0503-icon4a.gif",27,27,0,"","",0,0],200,0);
stm_ai("p1i2",[6,1,"#000000","",-1,-1,0]);
stm_aix("p1i3","p1i1",[0,"E-mail","","",-1,-1,0,"","_self","","","0503-icon5.gif","0503-icon5a.gif"],200,0);
stm_aix("p1i4","p1i3",[0,"Menu Item 2"],200,0);
stm_aix("p1i5","p1i1",[0,"Windows Media Player","","",-1,-1,0,"","_self","","","0503-icon3.gif","0503-icon3a.gif"],200,0);
stm_aix("p1i6","p1i1",[0,"Windows Update","","",-1,-1,0,"","_self","","","0503-icon2.gif","0503-icon2a.gif"],200,0);
stm_ep();
*/

stm_ai("p1i2",[6,1,"#000000","",-1,-1,0]);
stm_aix("p1i1","p1i0",[1,"&nbsp;<a  href=\"mailto:Kokrashvili@gmail.com\">Kokrashvili@gmail.com</a>","","",-1,-1,0,"","_self","","","email.gif","email.gif",27,27,0,"","",0,0],210,0);
stm_ai("p1i2",[6,1,"#000000","",-1,-1,0]);
stm_aix("p1i3","p1i1",[1,"&nbsp;IrakliKokrashvili@hotmail.com","","",-1,-1,0,"","_self","","","msn.gif","msn.gif",27,27,0,"","",0,0],210,0);
stm_aix("p1i4","p1i1",[1,"&nbsp;17409165","","",-1,-1,0,"","_self","","","icq.gif","icq.gif",27,27,0,"","",0,0],210,0);
stm_aix("p1i5","p1i1",[1,"&nbsp;IkaBika_1977","","",-1,-1,0,"","_self","","","yahoo.gif","yahoo.gif",27,27,0,"","",0,0],210,0);
stm_aix("p1i6","p1i1",[1,"&nbsp;Irakli_1977","","",-1,-1,0,"","_self","","","skype.gif","skype.gif",27,27,0,"","",0,0],210,0);
stm_aix("p1i7","p1i1",[1,"&nbsp;Kokrashvili@gmail.com","","",-1,-1,0,"","_self","","","googletalk.gif","googletalk.gif",27,27,0,"","",0,0],210,0);
stm_ai("p1i8",[6,1,"#000000","",-1,-1,0]);


stm_aix("p1i9","p1i1",[1,"<a  class=\"menuItem\" href=\"apps/devcpp-4.9.9.2_setup.exe\">&nbsp;&nbsp;<strong>Dev-C++ 9.2 (4.9.9.2)</strong></a>","","",-1,-1,0,"","_self","","","devcpp.gif","devcpp.gif",27,27	,0,"","",0,0],210,0);
stm_aix("p1i10","p1i1",[1,"<a  class=\"menuItem\" href=\"files/glut32.dll\">&nbsp;&nbsp;<strong>glut32.dll</strong></a>","","",-1,-1,0,"","_self","","","dll.gif","dll.gif",27,27	,0,"","",0,0],210,0);
stm_aix("p1i11","p1i1",[1,"<a  class=\"menuItem\" href=\"apps/libs.zip\">&nbsp;&nbsp;<strong>Dev-C++ libs</strong></a>","","",-1,-1,0,"","_self","","","winzip.gif","winzip.gif",27,27	,0,"","",0,0],210,0);
stm_aix("p1i12","p1i1",[1,"<a  class=\"menuItem\" href=\"apps/regfps292.exe\">&nbsp;&nbsp;<strong>Fraps 2.9.2</strong></a>","","",-1,-1,0,"","_self","","","fraps.gif","fraps.gif",27,27	,0,"","",0,0],210,0);
stm_aix("p1i13","p1i1",[1,"<a  class=\"menuItem\" href=\"apps/IrfanView.exe\">&nbsp;&nbsp;<strong>IrfanView 4.0</strong></a>","","",-1,-1,0,"","_self","","","irfan.gif","irfan.gif",27,27	,0,"","",0,0],210,0);

stm_ai("p1i14",[6,1,"#000000","",-1,-1,0]);
stm_aix("p1i15","p1i1",[1,"&nbsp;&nbsp;<a href=\"javascript:openMozilla('http://www.opengl.org');\">OpenGL.org</a>","","",-1,-1,0,"","_self","","","opengl.gif","opengl.gif",61,27,0,"","",0,0],210,0);
stm_aix("p1i16","p1i1",[1,"&nbsp;&nbsp;<a href=\"javascript:openMozilla('http://www.khronos.org/');\">Khronos.org</a>","","",-1,-1,0,"","_self","","","khronos.gif","khronos.gif",61,27,0,"","",0,0],210,0);
stm_aix("p1i17","p1i1",[1,"&nbsp;&nbsp;<a href=\"javascript:openMozilla('http://nehe.gamedev.net/');\">Nehe Tutorials</a>","","",-1,-1,0,"","_self","","","nehe.gif","nehe.gif",61,27,0,"","",0,0],210,0);
stm_aix("p1i18","p1i1",[1,"&nbsp;&nbsp;<a href=\"javascript:openMozilla('http://www.lighthouse3d.com/opengl/');\">Lighthouse 3D</a>","","",-1,-1,0,"","_self","","","opengl.gif","opengl.gif",61,27,0,"","",0,0],210,0);
stm_aix("p1i19","p1i1",[1,"&nbsp;&nbsp;<a href=\"javascript:openMozilla('http://www.ozone3d.net/tutorials/index.php');\">oZone3D.Net</a>","","",-1,-1,0,"","_self","","","ozone3d.gif","ozone3d.gif",61,27,0,"","",0,0],210,0);
stm_aix("p1i20","p1i1",[1,"&nbsp;&nbsp;<a href=\"javascript:openMozilla('http://www.devmaster.net/');\">devmaster.net</a>","","",-1,-1,0,"","_self","","","devmaster.gif","devmaster.gif",61,27,0,"","",0,0],210,0);
stm_aix("p1i21","p1i1",[1,"&nbsp;&nbsp;<a href=\"javascript:openMozilla('http://www.gamedev.net/');\">Gamedev.net</a>","","",-1,-1,0,"","_self","","","gamedev.gif","gamedev.gif",61,27,0,"","",0,0],210,0);
stm_ai("p1i22",[6,1,"#000000","",-1,-1,0]);	
stm_aix("p1i23","p1i1",[1,"&nbsp;&nbsp;<a class=\"menuItem\" href=\"javascript:Reboot();\"><strong> Reboot </strong></a>","","",-1,-1,0,"","_self","","","reboot.gif","reboot.gif",27,27,0,"","",0,0],210,0);


stm_ep();
stm_sc(1,["transparent","transparent","","",3,3,0,0,"#fffff7","#000000","up_disabled.gif","black-r.gif",7,7,0,"down_disabled.gif","down_enabled.gif",7,9,0,0,1]);
stm_em();
